-- Автосгенерировано content/components/make_seed.py из selection.json + aitmpl_catalog.csv.
-- НЕ редактировать руками — правь selection.json и перегенерируй.
-- Идемпотентно: ON CONFLICT (slug) DO UPDATE, published не трогается при повторном прогоне.
-- Применить: psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f content/components/cc_components_seed.sql

BEGIN;

INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-cloud-architect', 'agents', 'devops-infrastructure', 'cloud-architect', 'cloud-architect', 'Проектирование облачной инфраструктуры', 'npx claude-code-templates@latest --agent devops-infrastructure/cloud-architect --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/devops-infrastructure/cloud-architect.md', 0)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-code-reviewer', 'agents', 'development-tools', 'code-reviewer', 'code-reviewer', 'Сеньор-ревьюер: качество, безопасность и производительность кода в одном проходе', 'npx claude-code-templates@latest --agent development-tools/code-reviewer --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/development-tools/code-reviewer.md', 1)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-code-simplifier', 'agents', 'development-tools', 'code-simplifier', 'code-simplifier', 'Упрощение переусложнённого кода без потери логики', 'npx claude-code-templates@latest --agent development-tools/code-simplifier --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/development-tools/code-simplifier.md', 2)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-codebase-explorer', 'agents', 'development-tools', 'codebase-explorer', 'codebase-explorer', 'Быстрая карта незнакомой кодовой базы', 'npx claude-code-templates@latest --agent development-tools/codebase-explorer --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/development-tools/codebase-explorer.md', 3)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-database-optimizer', 'agents', 'database', 'database-optimizer', 'database-optimizer', 'Оптимизация схем и медленных запросов', 'npx claude-code-templates@latest --agent database/database-optimizer --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/database/database-optimizer.md', 4)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-debugger', 'agents', 'development-tools', 'debugger', 'debugger', 'Систематическая отладка: от симптома к первопричине по шагам', 'npx claude-code-templates@latest --agent development-tools/debugger --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/development-tools/debugger.md', 5)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-deployment-engineer', 'agents', 'devops-infrastructure', 'deployment-engineer', 'deployment-engineer', 'CI/CD-пайплайны и стратегии деплоя', 'npx claude-code-templates@latest --agent devops-infrastructure/deployment-engineer --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/devops-infrastructure/deployment-engineer.md', 6)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-devops-troubleshooter', 'agents', 'devops-infrastructure', 'devops-troubleshooter', 'devops-troubleshooter', 'Диагностика инцидентов в проде: логи, метрики, гипотезы', 'npx claude-code-templates@latest --agent devops-infrastructure/devops-troubleshooter --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/devops-infrastructure/devops-troubleshooter.md', 7)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-error-detective', 'agents', 'development-tools', 'error-detective', 'error-detective', 'Разбор логов и стектрейсов, поиск корня ошибки', 'npx claude-code-templates@latest --agent development-tools/error-detective --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/development-tools/error-detective.md', 8)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-golang-pro', 'agents', 'programming-languages', 'golang-pro', 'golang-pro', 'Go: конкурентность, интерфейсы, производительность', 'npx claude-code-templates@latest --agent programming-languages/golang-pro --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/programming-languages/golang-pro.md', 9)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-incident-responder', 'agents', 'devops-infrastructure', 'incident-responder', 'incident-responder', 'Действия при инциденте: триаж, эскалация, постмортем', 'npx claude-code-templates@latest --agent security/incident-responder --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/security/incident-responder.md', 10)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-javascript-pro', 'agents', 'programming-languages', 'javascript-pro', 'javascript-pro', 'Современный JavaScript: ES2024+, паттерны, производительность', 'npx claude-code-templates@latest --agent programming-languages/javascript-pro --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/programming-languages/javascript-pro.md', 11)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-kubernetes-specialist', 'agents', 'devops-infrastructure', 'kubernetes-specialist', 'kubernetes-specialist', 'Kubernetes: манифесты, отладка, оптимизация кластера', 'npx claude-code-templates@latest --agent devops-infrastructure/kubernetes-specialist --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/devops-infrastructure/kubernetes-specialist.md', 12)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-llm-redteam-specialist', 'agents', 'security', 'llm-redteam-specialist', 'llm-redteam-specialist', 'Red-team для LLM-приложений: промпт-инъекции и джейлбрейки', 'npx claude-code-templates@latest --agent security/llm-redteam-specialist --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/security/llm-redteam-specialist.md', 13)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-mcp-expert', 'agents', 'development-tools', 'mcp-expert', 'mcp-expert', 'Помощник по разработке собственных MCP-серверов', 'npx claude-code-templates@latest --agent development-tools/mcp-expert --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/development-tools/mcp-expert.md', 14)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-monitoring-specialist', 'agents', 'devops-infrastructure', 'monitoring-specialist', 'monitoring-specialist', 'Метрики, дашборды, алёртинг', 'npx claude-code-templates@latest --agent devops-infrastructure/monitoring-specialist --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/devops-infrastructure/monitoring-specialist.md', 15)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-nextjs-developer', 'agents', 'programming-languages', 'nextjs-developer', 'nextjs-developer', 'Next.js: SSR, роутинг, оптимизация', 'npx claude-code-templates@latest --agent programming-languages/nextjs-developer --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/programming-languages/nextjs-developer.md', 16)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-penetration-tester', 'agents', 'security', 'penetration-tester', 'penetration-tester', 'Пентест-подход: поиск векторов атаки в своём приложении', 'npx claude-code-templates@latest --agent security/penetration-tester --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/security/penetration-tester.md', 17)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-performance-engineer', 'agents', 'development-tools', 'performance-engineer', 'performance-engineer', 'Профилирование и устранение узких мест производительности', 'npx claude-code-templates@latest --agent performance-testing/performance-engineer --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/performance-testing/performance-engineer.md', 18)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-postgres-pro', 'agents', 'database', 'postgres-pro', 'postgres-pro', 'Глубокая экспертиза PostgreSQL: запросы, индексы, тюнинг', 'npx claude-code-templates@latest --agent database/postgres-pro --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/database/postgres-pro.md', 19)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-python-pro', 'agents', 'programming-languages', 'python-pro', 'python-pro', 'Идиоматичный Python: типизация, асинхронность, структура проекта', 'npx claude-code-templates@latest --agent programming-languages/python-pro --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/programming-languages/python-pro.md', 20)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-qa-expert', 'agents', 'development-tools', 'qa-expert', 'qa-expert', 'Тест-планы, граничные случаи, регрессионное покрытие', 'npx claude-code-templates@latest --agent development-tools/qa-expert --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/development-tools/qa-expert.md', 21)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-react-specialist', 'agents', 'programming-languages', 'react-specialist', 'react-specialist', 'React: хуки, состояние, производительность', 'npx claude-code-templates@latest --agent programming-languages/react-specialist --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/programming-languages/react-specialist.md', 22)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-refactoring-specialist', 'agents', 'development-tools', 'refactoring-specialist', 'refactoring-specialist', 'Безопасный рефакторинг без изменения поведения', 'npx claude-code-templates@latest --agent development-tools/refactoring-specialist --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/development-tools/refactoring-specialist.md', 23)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-rust-engineer', 'agents', 'programming-languages', 'rust-engineer', 'rust-engineer', 'Rust: владение, lifetimes, безопасный системный код', 'npx claude-code-templates@latest --agent programming-languages/rust-engineer --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/programming-languages/rust-engineer.md', 24)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-security-auditor', 'agents', 'security', 'security-auditor', 'security-auditor', 'Аудит безопасности кода и конфигураций', 'npx claude-code-templates@latest --agent security/security-auditor --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/security/security-auditor.md', 25)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-shell-scripting-pro', 'agents', 'programming-languages', 'shell-scripting-pro', 'shell-scripting-pro', 'Надёжные bash-скрипты для автоматизации', 'npx claude-code-templates@latest --agent programming-languages/shell-scripting-pro --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/programming-languages/shell-scripting-pro.md', 26)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-sql-pro', 'agents', 'programming-languages', 'sql-pro', 'sql-pro', 'Сложный SQL: оконные функции, CTE, планы выполнения', 'npx claude-code-templates@latest --agent programming-languages/sql-pro --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/programming-languages/sql-pro.md', 27)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-sre-engineer', 'agents', 'devops-infrastructure', 'sre-engineer', 'sre-engineer', 'SLO, алёртинг и надёжность как инженерная практика', 'npx claude-code-templates@latest --agent devops-infrastructure/sre-engineer --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/devops-infrastructure/sre-engineer.md', 28)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-technical-debt-manager', 'agents', 'development-tools', 'technical-debt-manager', 'technical-debt-manager', 'Инвентаризация и приоритизация техдолга', 'npx claude-code-templates@latest --agent development-tools/technical-debt-manager --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/development-tools/technical-debt-manager.md', 29)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-terraform-specialist', 'agents', 'devops-infrastructure', 'terraform-specialist', 'terraform-specialist', 'Terraform: модули, state, ревью планов', 'npx claude-code-templates@latest --agent devops-infrastructure/terraform-specialist --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/devops-infrastructure/terraform-specialist.md', 30)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-test-automator', 'agents', 'development-tools', 'test-automator', 'test-automator', 'Автоматизация тестирования: генерация и поддержка тестовых наборов', 'npx claude-code-templates@latest --agent performance-testing/test-automator --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/performance-testing/test-automator.md', 31)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-typescript-pro', 'agents', 'programming-languages', 'typescript-pro', 'typescript-pro', 'Строгий TypeScript: типы, генерики, конфигурация', 'npx claude-code-templates@latest --agent programming-languages/typescript-pro --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/programming-languages/typescript-pro.md', 32)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-agent-unused-code-cleaner', 'agents', 'development-tools', 'unused-code-cleaner', 'unused-code-cleaner', 'Поиск и удаление мёртвого кода', 'npx claude-code-templates@latest --agent development-tools/unused-code-cleaner --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/agents/development-tools/unused-code-cleaner.md', 33)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-branch-cleanup', 'commands', 'git-workflow', 'branch-cleanup', 'branch-cleanup', 'Чистка отработанных веток', 'npx claude-code-templates@latest --command git-workflow/branch-cleanup --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/git-workflow/branch-cleanup.md', 1000)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-ci-setup', 'commands', 'deployment', 'ci-setup', 'ci-setup', 'Настройка CI-пайплайна под проект', 'npx claude-code-templates@latest --command deployment/ci-setup --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/deployment/ci-setup.md', 1001)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-commit', 'commands', 'git-workflow', 'commit', 'commit', 'Умный коммит: анализ диффа и сообщение по Conventional Commits', 'npx claude-code-templates@latest --command orchestration/commit --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/orchestration/commit.md', 1002)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-containerize-application', 'commands', 'deployment', 'containerize-application', 'containerize-application', 'Dockerfile и compose для приложения', 'npx claude-code-templates@latest --command deployment/containerize-application --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/deployment/containerize-application.md', 1003)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-create-pr', 'commands', 'git-workflow', 'create-pr', 'create-pr', 'Создание pull request с описанием из изменений', 'npx claude-code-templates@latest --command git-workflow/create-pr --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/git-workflow/create-pr.md', 1004)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-create-worktrees', 'commands', 'git-workflow', 'create-worktrees', 'create-worktrees', 'Git worktrees для параллельных сессий Claude Code', 'npx claude-code-templates@latest --command git-workflow/create-worktrees --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/git-workflow/create-worktrees.md', 1005)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-dependency-audit', 'commands', 'security', 'dependency-audit', 'dependency-audit', 'Проверка зависимостей на известные CVE', 'npx claude-code-templates@latest --command security/dependency-audit --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/security/dependency-audit.md', 1006)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-e2e-setup', 'commands', 'testing', 'e2e-setup', 'e2e-setup', 'Настройка E2E-тестирования с нуля', 'npx claude-code-templates@latest --command testing/e2e-setup --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/testing/e2e-setup.md', 1007)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-fix-github-issue', 'commands', 'git-workflow', 'fix-github-issue', 'fix-github-issue', 'Взять issue из GitHub и довести до фикса', 'npx claude-code-templates@latest --command git-workflow/fix-github-issue --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/git-workflow/fix-github-issue.md', 1008)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-generate-api-documentation', 'commands', 'documentation', 'generate-api-documentation', 'generate-api-documentation', 'Генерация документации API из кода', 'npx claude-code-templates@latest --command documentation/generate-api-documentation --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/documentation/generate-api-documentation.md', 1009)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-generate-test-cases', 'commands', 'testing', 'generate-test-cases', 'generate-test-cases', 'Тест-кейсы из требований', 'npx claude-code-templates@latest --command testing/generate-test-cases --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/testing/generate-test-cases.md', 1010)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-generate-tests', 'commands', 'testing', 'generate-tests', 'generate-tests', 'Генерация тестов для выбранного кода', 'npx claude-code-templates@latest --command testing/generate-tests --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/testing/generate-tests.md', 1011)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-hotfix-deploy', 'commands', 'deployment', 'hotfix-deploy', 'hotfix-deploy', 'Быстрый хотфикс в прод по процедуре', 'npx claude-code-templates@latest --command deployment/hotfix-deploy --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/deployment/hotfix-deploy.md', 1012)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-optimize-bundle-size', 'commands', 'performance', 'optimize-bundle-size', 'optimize-bundle-size', 'Уменьшение размера фронтенд-бандла', 'npx claude-code-templates@latest --command performance/optimize-bundle-size --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/performance/optimize-bundle-size.md', 1013)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-optimize-database-performance', 'commands', 'performance', 'optimize-database-performance', 'optimize-database-performance', 'Оптимизация работы приложения с БД', 'npx claude-code-templates@latest --command performance/optimize-database-performance --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/performance/optimize-database-performance.md', 1014)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-performance-audit', 'commands', 'performance', 'performance-audit', 'performance-audit', 'Полный аудит производительности', 'npx claude-code-templates@latest --command performance/performance-audit --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/performance/performance-audit.md', 1015)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-pr-review', 'commands', 'git-workflow', 'pr-review', 'pr-review', 'Ревью пул-реквеста по чек-листу', 'npx claude-code-templates@latest --command git-workflow/pr-review --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/git-workflow/pr-review.md', 1016)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-prepare-release', 'commands', 'deployment', 'prepare-release', 'prepare-release', 'Подготовка релиза: версия, ченджлог, теги', 'npx claude-code-templates@latest --command deployment/prepare-release --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/deployment/prepare-release.md', 1017)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-rollback-deploy', 'commands', 'deployment', 'rollback-deploy', 'rollback-deploy', 'Безопасный откат релиза', 'npx claude-code-templates@latest --command deployment/rollback-deploy --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/deployment/rollback-deploy.md', 1018)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-secrets-scanner', 'commands', 'security', 'secrets-scanner', 'secrets-scanner', 'Поиск утёкших секретов в коде', 'npx claude-code-templates@latest --command security/secrets-scanner --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/security/secrets-scanner.md', 1019)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-security-audit', 'commands', 'security', 'security-audit', 'security-audit', 'Аудит безопасности проекта одной командой', 'npx claude-code-templates@latest --command security/security-audit --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/security/security-audit.md', 1020)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-setup-load-testing', 'commands', 'testing', 'setup-load-testing', 'setup-load-testing', 'Нагрузочное тестирование: инструменты и сценарии', 'npx claude-code-templates@latest --command testing/setup-load-testing --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/testing/setup-load-testing.md', 1021)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-supply-chain-audit', 'commands', 'analysis', 'supply-chain-audit', 'supply-chain-audit', 'Аудит цепочки поставок зависимостей', 'npx claude-code-templates@latest --command analysis/supply-chain-audit --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/analysis/supply-chain-audit.md', 1022)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-command-update-docs', 'commands', 'documentation', 'update-docs', 'update-docs', 'Актуализация документации по текущему коду', 'npx claude-code-templates@latest --command documentation/update-docs --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/commands/documentation/update-docs.md', 1023)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-mcp-arxiv-mcp-server', 'mcps', 'research', 'arxiv-mcp-server', 'arxiv-mcp-server', 'Поиск и выгрузка статей arXiv', 'npx claude-code-templates@latest --mcp research/arxiv-mcp-server --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/mcps/research/arxiv-mcp-server.json', 2000)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-mcp-context7', 'mcps', 'devtools', 'context7', 'context7', 'Актуальная документация библиотек прямо в контекст', 'npx claude-code-templates@latest --mcp devtools/context7 --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/mcps/devtools/context7.json', 2001)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-mcp-elasticsearch', 'mcps', 'devtools', 'elasticsearch', 'elasticsearch', 'Поиск и агрегации Elasticsearch', 'npx claude-code-templates@latest --mcp devtools/elasticsearch --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/mcps/devtools/elasticsearch.json', 2002)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-mcp-filesystem-access', 'mcps', 'filesystem', 'filesystem-access', 'filesystem-access', 'Контролируемый доступ к файловой системе', 'npx claude-code-templates@latest --mcp filesystem/filesystem-access --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/mcps/filesystem/filesystem-access.json', 2003)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-mcp-github-official', 'mcps', 'devtools', 'github-official', 'github-official', 'Официальный GitHub MCP: issues, PR, репозитории', 'npx claude-code-templates@latest --mcp devtools/github-official --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/mcps/devtools/github-official.json', 2004)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-mcp-grafana', 'mcps', 'devtools', 'grafana', 'grafana', 'Дашборды и метрики Grafana', 'npx claude-code-templates@latest --mcp devtools/grafana --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/mcps/devtools/grafana.json', 2005)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-mcp-markitdown', 'mcps', 'devtools', 'markitdown', 'markitdown', 'Конвертация документов в Markdown (Microsoft)', 'npx claude-code-templates@latest --mcp devtools/markitdown --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/mcps/devtools/markitdown.json', 2006)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-mcp-mermaid', 'mcps', 'devtools', 'mermaid', 'mermaid', 'Рендер диаграмм Mermaid', 'npx claude-code-templates@latest --mcp devtools/mermaid --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/mcps/devtools/mermaid.json', 2007)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-mcp-mongodb-official', 'mcps', 'database', 'mongodb-official', 'mongodb-official', 'Официальный MCP-сервер MongoDB', 'npx claude-code-templates@latest --mcp database/mongodb-official --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/mcps/database/mongodb-official.json', 2008)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-mcp-n8n-mcp', 'mcps', 'integration', 'n8n-mcp', 'n8n-mcp', 'Связка Claude с автоматизациями n8n', 'npx claude-code-templates@latest --mcp integration/n8n-mcp --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/mcps/integration/n8n-mcp.json', 2009)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-mcp-notion', 'mcps', 'productivity', 'notion', 'notion', 'Notion: страницы и базы данных', 'npx claude-code-templates@latest --mcp productivity/notion --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/mcps/productivity/notion.json', 2010)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-mcp-playwright-mcp', 'mcps', 'browser_automation', 'playwright-mcp', 'playwright-mcp', 'Управление браузером через Playwright', 'npx claude-code-templates@latest --mcp browser_automation/playwright-mcp --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/mcps/browser_automation/playwright-mcp.json', 2011)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-mcp-postgresql-integration', 'mcps', 'database', 'postgresql-integration', 'postgresql-integration', 'Claude подключается к PostgreSQL: запросы и схема', 'npx claude-code-templates@latest --mcp database/postgresql-integration --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/mcps/database/postgresql-integration.json', 2012)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-mcp-postman', 'mcps', 'devtools', 'postman', 'postman', 'Коллекции и запросы Postman', 'npx claude-code-templates@latest --mcp devtools/postman --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/mcps/devtools/postman.json', 2013)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-mcp-redis', 'mcps', 'database', 'redis', 'redis', 'Работа с Redis из Claude', 'npx claude-code-templates@latest --mcp database/redis --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/mcps/database/redis.json', 2014)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-mcp-searxng', 'mcps', 'web', 'searxng', 'searxng', 'Приватный веб-поиск через SearXNG', 'npx claude-code-templates@latest --mcp web/searxng --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/mcps/web/searxng.json', 2015)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-mcp-sentry', 'mcps', 'devtools', 'sentry', 'sentry', 'Ошибки и трейсы Sentry внутри Claude', 'npx claude-code-templates@latest --mcp devtools/sentry --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/mcps/devtools/sentry.json', 2016)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-mcp-stripe', 'mcps', 'devtools', 'stripe', 'stripe', 'Объекты и аналитика Stripe', 'npx claude-code-templates@latest --mcp devtools/stripe --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/mcps/devtools/stripe.json', 2017)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-mcp-supabase', 'mcps', 'database', 'supabase', 'supabase', 'Управление Supabase-проектом', 'npx claude-code-templates@latest --mcp database/supabase --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/mcps/database/supabase.json', 2018)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-skill-api-design-principles', 'skills', 'development', 'api-design-principles', 'api-design-principles', 'Принципы проектирования API', 'npx claude-code-templates@latest --skill development/api-design-principles --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/skills/development/api-design-principles', 3000)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-skill-architecture-decision-records', 'skills', 'development', 'architecture-decision-records', 'architecture-decision-records', 'ADR: фиксация архитектурных решений', 'npx claude-code-templates@latest --skill development/architecture-decision-records --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/skills/development/architecture-decision-records', 3001)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-skill-async-python-patterns', 'skills', 'development', 'async-python-patterns', 'async-python-patterns', 'Паттерны асинхронного Python', 'npx claude-code-templates@latest --skill development/async-python-patterns --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/skills/development/async-python-patterns', 3002)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-skill-changelog-generator', 'skills', 'development', 'changelog-generator', 'changelog-generator', 'Генерация ченджлогов', 'npx claude-code-templates@latest --skill development/changelog-generator --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/skills/development/changelog-generator', 3003)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-skill-clean-code', 'skills', 'development', 'clean-code', 'clean-code', 'Практики чистого кода', 'npx claude-code-templates@latest --skill development/clean-code --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/skills/development/clean-code', 3004)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-skill-code-review-checklist', 'skills', 'development', 'code-review-checklist', 'code-review-checklist', 'Чек-лист код-ревью', 'npx claude-code-templates@latest --skill development/code-review-checklist --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/skills/development/code-review-checklist', 3005)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-skill-commit-work', 'skills', 'productivity', 'commit-work', 'commit-work', 'Дисциплина коммитов в агентной работе', 'npx claude-code-templates@latest --skill productivity/commit-work --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/skills/productivity/commit-work', 3006)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-skill-debugging-strategies', 'skills', 'productivity', 'debugging-strategies', 'debugging-strategies', 'Стратегии отладки', 'npx claude-code-templates@latest --skill productivity/debugging-strategies --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/skills/productivity/debugging-strategies', 3007)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-skill-docx-official', 'skills', 'document-processing', 'docx-official', 'docx-official', 'Word-документы (официальный скилл Anthropic)', 'npx claude-code-templates@latest --skill document-processing/docx-official --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/skills/document-processing/docx-official', 3008)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-skill-github-actions-templates', 'skills', 'workflow-automation', 'github-actions-templates', 'github-actions-templates', 'Шаблоны GitHub Actions', 'npx claude-code-templates@latest --skill workflow-automation/github-actions-templates --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/skills/workflow-automation/github-actions-templates', 3009)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-skill-n8n-workflow-patterns', 'skills', 'workflow-automation', 'n8n-workflow-patterns', 'n8n-workflow-patterns', 'Паттерны воркфлоу n8n', 'npx claude-code-templates@latest --skill workflow-automation/n8n-workflow-patterns --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/skills/workflow-automation/n8n-workflow-patterns', 3010)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-skill-pdf-official', 'skills', 'document-processing', 'pdf-official', 'pdf-official', 'Работа с PDF: чтение, формы, генерация (официальный скилл Anthropic)', 'npx claude-code-templates@latest --skill document-processing/pdf-official --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/skills/document-processing/pdf-official', 3011)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-skill-plan-writing', 'skills', 'productivity', 'plan-writing', 'plan-writing', 'Написание рабочих планов', 'npx claude-code-templates@latest --skill productivity/plan-writing --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/skills/productivity/plan-writing', 3012)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-skill-pptx-official', 'skills', 'document-processing', 'pptx-official', 'pptx-official', 'Презентации PowerPoint (официальный скилл Anthropic)', 'npx claude-code-templates@latest --skill document-processing/pptx-official --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/skills/document-processing/pptx-official', 3013)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-skill-skill-creator', 'skills', 'productivity', 'skill-creator', 'skill-creator', 'Создание собственных скиллов', 'npx claude-code-templates@latest --skill productivity/skill-creator --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/skills/productivity/skill-creator', 3014)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-skill-xlsx-official', 'skills', 'document-processing', 'xlsx-official', 'xlsx-official', 'Excel-таблицы (официальный скилл Anthropic)', 'npx claude-code-templates@latest --skill document-processing/xlsx-official --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/skills/document-processing/xlsx-official', 3015)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-hook-conventional-commits', 'hooks', 'git', 'conventional-commits', 'conventional-commits', 'Валидация сообщений коммитов по конвенции', 'npx claude-code-templates@latest --hook git/conventional-commits --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/hooks/git/conventional-commits.json', 4000)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-hook-dangerous-command-blocker', 'hooks', 'security', 'dangerous-command-blocker', 'dangerous-command-blocker', 'Блокировка опасных bash-команд (rm -rf и подобных)', 'npx claude-code-templates@latest --hook security/dangerous-command-blocker --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/hooks/security/dangerous-command-blocker.json', 4001)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-hook-desktop-notification-on-stop', 'hooks', 'monitoring', 'desktop-notification-on-stop', 'desktop-notification-on-stop', 'Десктоп-уведомление о завершении работы', 'npx claude-code-templates@latest --hook monitoring/desktop-notification-on-stop --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/hooks/monitoring/desktop-notification-on-stop.json', 4002)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-hook-env-file-protection', 'hooks', 'security', 'env-file-protection', 'env-file-protection', 'Защита .env-файлов от чтения и правок', 'npx claude-code-templates@latest --hook security/env-file-protection --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/hooks/security/env-file-protection.json', 4003)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-hook-force-push-blocker', 'hooks', 'security', 'force-push-blocker', 'force-push-blocker', 'Запрет force-push', 'npx claude-code-templates@latest --hook security/force-push-blocker --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/hooks/security/force-push-blocker.json', 4004)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-hook-prevent-direct-push', 'hooks', 'git', 'prevent-direct-push', 'prevent-direct-push', 'Блокировка прямых пушей в main', 'npx claude-code-templates@latest --hook git/prevent-direct-push --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/hooks/git/prevent-direct-push.json', 4005)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-hook-scope-guard', 'hooks', 'quality-gates', 'scope-guard', 'scope-guard', 'Контроль расползания скоупа задачи', 'npx claude-code-templates@latest --hook quality-gates/scope-guard --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/hooks/quality-gates/scope-guard.json', 4006)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-hook-secret-scanner', 'hooks', 'security', 'secret-scanner', 'secret-scanner', 'Скан секретов перед записью файлов', 'npx claude-code-templates@latest --hook security/secret-scanner --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/hooks/security/secret-scanner.json', 4007)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-hook-tdd-gate', 'hooks', 'quality-gates', 'tdd-gate', 'tdd-gate', 'TDD-ворота: сначала тест, потом код', 'npx claude-code-templates@latest --hook quality-gates/tdd-gate --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/hooks/quality-gates/tdd-gate.json', 4008)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-hook-telegram-detailed-notifications', 'hooks', 'automation', 'telegram-detailed-notifications', 'telegram-detailed-notifications', 'Подробные отчёты о работе Claude Code в Telegram', 'npx claude-code-templates@latest --hook automation/telegram-detailed-notifications --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/hooks/automation/telegram-detailed-notifications.json', 4009)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-hook-telegram-error-notifications', 'hooks', 'automation', 'telegram-error-notifications', 'telegram-error-notifications', 'Алёрты об ошибках сессии в Telegram', 'npx claude-code-templates@latest --hook automation/telegram-error-notifications --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/hooks/automation/telegram-error-notifications.json', 4010)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-hook-telegram-notifications', 'hooks', 'automation', 'telegram-notifications', 'telegram-notifications', 'Уведомления в Telegram о событиях сессии Claude Code', 'npx claude-code-templates@latest --hook automation/telegram-notifications --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/hooks/automation/telegram-notifications.json', 4011)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-hook-telegram-pr-webhook', 'hooks', 'automation', 'telegram-pr-webhook', 'telegram-pr-webhook', 'Вебхук о созданных PR в Telegram', 'npx claude-code-templates@latest --hook automation/telegram-pr-webhook --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/hooks/automation/telegram-pr-webhook.json', 4012)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-hook-validate-branch-name', 'hooks', 'git', 'validate-branch-name', 'validate-branch-name', 'Проверка имени ветки по шаблону', 'npx claude-code-templates@latest --hook git/validate-branch-name --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/hooks/git/validate-branch-name.json', 4013)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-setting-allow-git-operations', 'settings', 'permissions', 'allow-git-operations', 'allow-git-operations', 'Git-операции без запроса подтверждений', 'npx claude-code-templates@latest --setting permissions/allow-git-operations --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/settings/permissions/allow-git-operations.json', 5000)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-setting-bash-timeouts', 'settings', 'environment', 'bash-timeouts', 'bash-timeouts', 'Таймауты выполнения bash-команд', 'npx claude-code-templates@latest --setting environment/bash-timeouts --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/settings/environment/bash-timeouts.json', 5001)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-setting-context-monitor', 'settings', 'statusline', 'context-monitor', 'context-monitor', 'Статус-бар: расход контекстного окна', 'npx claude-code-templates@latest --setting statusline/context-monitor --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/settings/statusline/context-monitor.json', 5002)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-setting-deny-sensitive-files', 'settings', 'permissions', 'deny-sensitive-files', 'deny-sensitive-files', 'Запрет доступа к чувствительным файлам', 'npx claude-code-templates@latest --setting permissions/deny-sensitive-files --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/settings/permissions/deny-sensitive-files.json', 5003)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-setting-git-branch-statusline', 'settings', 'statusline', 'git-branch-statusline', 'git-branch-statusline', 'Ветка и статус git в статус-баре', 'npx claude-code-templates@latest --setting statusline/git-branch-statusline --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/settings/statusline/git-branch-statusline.json', 5004)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-setting-minimal-statusline', 'settings', 'statusline', 'minimal-statusline', 'minimal-statusline', 'Минималистичный статус-бар', 'npx claude-code-templates@latest --setting statusline/minimal-statusline --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/settings/statusline/minimal-statusline.json', 5005)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-setting-privacy-focused', 'settings', 'environment', 'privacy-focused', 'privacy-focused', 'Приватная конфигурация: телеметрия выключена', 'npx claude-code-templates@latest --setting environment/privacy-focused --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/settings/environment/privacy-focused.json', 5006)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-setting-read-only-mode', 'settings', 'permissions', 'read-only-mode', 'read-only-mode', 'Режим только чтение: без правок и команд', 'npx claude-code-templates@latest --setting permissions/read-only-mode --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/settings/permissions/read-only-mode.json', 5007)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-setting-use-haiku', 'settings', 'model', 'use-haiku', 'use-haiku', 'Haiku по умолчанию — для экономии на простых задачах', 'npx claude-code-templates@latest --setting model/use-haiku --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/settings/model/use-haiku.json', 5008)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-setting-use-sonnet', 'settings', 'model', 'use-sonnet', 'use-sonnet', 'Sonnet по умолчанию', 'npx claude-code-templates@latest --setting model/use-sonnet --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/settings/model/use-sonnet.json', 5009)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-loop-adversarial-review-loop', 'loops', 'engineering', 'adversarial-review-loop', 'adversarial-review-loop', 'Состязательное ревью: строитель против критика', 'npx claude-code-templates@latest --loop engineering/adversarial-review-loop --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/loops/engineering/adversarial-review-loop.md', 6000)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-loop-build-test-fix-loop', 'loops', 'engineering', 'build-test-fix-loop', 'build-test-fix-loop', 'Цикл build → test → fix до зелёного билда', 'npx claude-code-templates@latest --loop engineering/build-test-fix-loop --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/loops/engineering/build-test-fix-loop.md', 6001)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-loop-repo-cleanup-loop', 'loops', 'engineering', 'repo-cleanup-loop', 'repo-cleanup-loop', 'Итеративная чистка репозитория', 'npx claude-code-templates@latest --loop engineering/repo-cleanup-loop --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/loops/engineering/repo-cleanup-loop.md', 6002)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-loop-test-coverage-loop', 'loops', 'engineering', 'test-coverage-loop', 'test-coverage-loop', 'Итеративное наращивание покрытия тестами', 'npx claude-code-templates@latest --loop engineering/test-coverage-loop --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/loops/engineering/test-coverage-loop.md', 6003)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();
INSERT INTO baza.cc_components (slug, comp_type, category, name, title, summary, install_cmd, doc_url, sort_order) VALUES ('aitmpl-loop-ticket-to-pr-loop', 'loops', 'engineering', 'ticket-to-pr-loop', 'ticket-to-pr-loop', 'Из тикета в готовый PR автономно', 'npx claude-code-templates@latest --loop engineering/ticket-to-pr-loop --yes', 'https://github.com/davila7/claude-code-templates/blob/main/cli-tool/components/loops/engineering/ticket-to-pr-loop.md', 6004)
ON CONFLICT (slug) DO UPDATE SET comp_type = EXCLUDED.comp_type, category = EXCLUDED.category, name = EXCLUDED.name, title = EXCLUDED.title, summary = EXCLUDED.summary, install_cmd = EXCLUDED.install_cmd, doc_url = EXCLUDED.doc_url, sort_order = EXCLUDED.sort_order, updated_at = now();

COMMIT;
